// Copyright (c) Chris Wolfgang. All rights reserved. SPDX-License-Identifier: LicenseRef-TBD

using Microsoft.EntityFrameworkCore;
using Testcontainers.MsSql;
using Testcontainers.PostgreSql;
using Wolfgang.Wms.Infrastructure.Database;
using Wolfgang.Wms.Infrastructure.Database.Conventions;

namespace Wolfgang.Wms.IntegrationTests.Database;

/// <summary>
/// E5.1 against real engines: after the migrations (which create the sequence) a versioned table built with
/// the helper's SQL gets its <c>row_version</c> from the sequence on insert, the update trigger overwrites
/// any supplied value with a newer one, and versions are monotonic across tables. The trigger function and
/// SQL are the ones module migrations will call.
/// </summary>
public sealed class RowVersionTriggerTests
{
    [DockerFact]
    public async Task SqlServer_sequence_default_and_update_trigger_assign_monotonic_row_versions()
    {
        await using var container = new MsSqlBuilder("mcr.microsoft.com/mssql/server:2022-latest").Build();
        await container.StartAsync();

        await AssertRowVersioningAsync("SqlServer", container.GetConnectionString(), trustServerCertificate: true,
            createTable: "CREATE TABLE [picking].[thing] ([id] bigint IDENTITY(1,1) PRIMARY KEY, [name] nvarchar(50) NOT NULL, [row_version] bigint NOT NULL DEFAULT (NEXT VALUE FOR [wms].[row_version_seq]));",
            insert: "INSERT INTO [picking].[thing] ([name]) VALUES ('a'), ('b');",
            updateWithSuppliedVersion: "UPDATE [picking].[thing] SET [name] = 'a2', [row_version] = 1 WHERE [name] = 'a';",
            select: "SELECT [row_version] AS \"Value\" FROM [picking].[thing] ORDER BY [id]");
    }



    [DockerFact]
    public async Task PostgreSql_sequence_default_and_update_trigger_assign_monotonic_row_versions()
    {
        await using var container = new PostgreSqlBuilder("postgres:16").Build();
        await container.StartAsync();

        await AssertRowVersioningAsync("PostgreSql", container.GetConnectionString(), trustServerCertificate: false,
            createTable: "CREATE TABLE picking.thing (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL, row_version bigint NOT NULL DEFAULT nextval('wms.row_version_seq'));",
            insert: "INSERT INTO picking.thing (name) VALUES ('a'), ('b');",
            updateWithSuppliedVersion: "UPDATE picking.thing SET name = 'a2', row_version = 1 WHERE name = 'a';",
            select: "SELECT row_version AS \"Value\" FROM picking.thing ORDER BY id");
    }



    private static async Task AssertRowVersioningAsync(string provider, string connectionString, bool trustServerCertificate, string createTable, string insert, string updateWithSuppliedVersion, string select)
    {
        var builder = new DbContextOptionsBuilder<WmsDbContext>();
        DatabaseServiceCollectionExtensions.Configure(builder, new DatabaseOptions { Provider = provider, ConnectionString = connectionString, TrustServerCertificate = trustServerCertificate });
        using var context = new WmsDbContext(builder.Options);
        await context.Database.MigrateAsync();
        var providerName = context.Database.ProviderName!;
        var createSchema = string.Equals(provider, "SqlServer", StringComparison.Ordinal) ? "IF SCHEMA_ID('picking') IS NULL EXEC('CREATE SCHEMA [picking]');" : "CREATE SCHEMA IF NOT EXISTS picking;";

        await context.Database.ExecuteSqlRawAsync(createSchema);
        await context.Database.ExecuteSqlRawAsync(createTable);
        await context.Database.ExecuteSqlRawAsync(RowVersioning.UpdateTriggerSql(providerName, "picking", "thing"));
        await context.Database.ExecuteSqlRawAsync(insert);
        var inserted = await context.Database.SqlQueryRaw<long>(select).ToListAsync();
        await context.Database.ExecuteSqlRawAsync(updateWithSuppliedVersion);
        var updated = await context.Database.SqlQueryRaw<long>(select).ToListAsync();
        await context.Database.ExecuteSqlRawAsync(RowVersioning.DropTriggerSql(providerName, "picking", "thing"));

        Assert.Equal(2, inserted.Count);
        Assert.True(inserted[0] > 0 && inserted[1] > inserted[0], $"insert defaults: {string.Join(",", inserted)}");
        Assert.True(updated[0] > inserted[1], $"the trigger must overwrite the supplied value 1 with a newer version; got {updated[0]}");
        Assert.Equal(inserted[1], updated[1]);
    }
}
