// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Zones); index comments may be added (E3.5).
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Zones); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Wolfgang.Wms.Infrastructure.Database.Conventions;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.PostgreSql.Migrations
{
    /// <inheritdoc />
    public partial class Zones : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "zone",
                schema: "layout",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    site_id = table.Column<long>(type: "bigint", nullable: false),
                    code = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    code_normalized = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    name = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    type = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                    walk_order_prefix = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: true),
                    is_reject_lane = table.Column<bool>(type: "boolean", nullable: false),
                    restocking_bin = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    returns_container = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    accepts_weight_failures = table.Column<bool>(type: "boolean", nullable: false),
                    accepts_shorts = table.Column<bool>(type: "boolean", nullable: false),
                    accepts_adjustments = table.Column<bool>(type: "boolean", nullable: false),
                    accepts_misdirects = table.Column<bool>(type: "boolean", nullable: false),
                    is_virtual_queue = table.Column<bool>(type: "boolean", nullable: false),
                    is_active = table.Column<bool>(type: "boolean", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp(3) with time zone", precision: 3, nullable: false),
                    updated_by = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    row_version = table.Column<long>(type: "bigint", rowVersion: true, nullable: false, defaultValueSql: "nextval('wms.row_version_seq')")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_zone", x => x.id);
                    table.ForeignKey(
                        name: "fk_zone_site_id",
                        column: x => x.site_id,
                        principalSchema: "layout",
                        principalTable: "site",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "zone_resolver",
                schema: "layout",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    zone_id = table.Column<long>(type: "bigint", nullable: false),
                    user_id = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_zone_resolver", x => x.id);
                    table.ForeignKey(
                        name: "fk_zone_resolver_user_id",
                        column: x => x.user_id,
                        principalSchema: "core",
                        principalTable: "user",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_zone_resolver_zone_id",
                        column: x => x.zone_id,
                        principalSchema: "layout",
                        principalTable: "zone",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_zone_row_version",
                schema: "layout",
                table: "zone",
                column: "row_version");

            migrationBuilder.CreateIndex(
                name: "ux_zone_site_id_code_normalized",
                schema: "layout",
                table: "zone",
                columns: new[] { "site_id", "code_normalized" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_zone_resolver_user_id",
                schema: "layout",
                table: "zone_resolver",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ux_zone_resolver_zone_id_user_id",
                schema: "layout",
                table: "zone_resolver",
                columns: new[] { "zone_id", "user_id" },
                unique: true);

            // E5.1: the update trigger that reassigns row_version on every write outside EF and inside it.
            RowVersioning.AddUpdateTrigger(migrationBuilder, "layout", "zone");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            RowVersioning.DropUpdateTrigger(migrationBuilder, "layout", "zone");

            migrationBuilder.DropTable(
                name: "zone_resolver",
                schema: "layout");

            migrationBuilder.DropTable(
                name: "zone",
                schema: "layout");
        }
    }
}
