// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add CopiedFrom); index comments may be added (E3.5).
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.PostgreSql.Migrations
{
    /// <inheritdoc />
    public partial class CopiedFrom : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<long>(
                name: "copied_from_id",
                schema: "layout",
                table: "zone",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "copied_from_id",
                schema: "layout",
                table: "site",
                type: "bigint",
                nullable: true);

            migrationBuilder.AddColumn<long>(
                name: "copied_from_id",
                schema: "layout",
                table: "location",
                type: "bigint",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "copied_from_id",
                schema: "layout",
                table: "zone");

            migrationBuilder.DropColumn(
                name: "copied_from_id",
                schema: "layout",
                table: "site");

            migrationBuilder.DropColumn(
                name: "copied_from_id",
                schema: "layout",
                table: "location");
        }
    }
}
