// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wolfgang.Wms.Infrastructure.Database;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.PostgreSql.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20260920043257_Settings")]
    partial class Settings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("row_version_seq", "wms");

            modelBuilder.Entity("Wolfgang.Wms.Infrastructure.Database.Settings.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfiguredValue")
                        .HasColumnType("text")
                        .HasColumnName("configured_value");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EffectiveValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_value");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("nextval('wms.row_version_seq')");

                    b.Property<long>("ScopeId")
                        .HasColumnType("bigint")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_setting");

                    b.HasIndex("RowVersion")
                        .HasDatabaseName("ix_setting_row_version");

                    b.HasIndex("ScopeType", "ScopeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_setting_scope_type_scope_id_key");

                    b.ToTable("setting", "core", t =>
                        {
                            t.HasTrigger("trg_setting_row_version");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
