// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wolfgang.Wms.Infrastructure.Database;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.PostgreSql.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20260920054534_DataProtectionKeys")]
    partial class DataProtectionKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("row_version_seq", "wms");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_key");

                    b.ToTable("data_protection_key", "wms");
                });

            modelBuilder.Entity("Wolfgang.AuditTrail.Entities.AuditDetail", b =>
                {
                    b.Property<long>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("detail_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DetailId"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("column_name");

                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("header_id");

                    b.Property<string>("ValueText")
                        .HasColumnType("text")
                        .HasColumnName("value_text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("value_type");

                    b.HasKey("DetailId")
                        .HasName("pk_audit_detail");

                    b.HasIndex("ColumnName")
                        .HasDatabaseName("ix_audit_detail_column_name");

                    b.HasIndex("HeaderId")
                        .HasDatabaseName("ix_audit_detail_header_id");

                    b.ToTable("audit_detail", "core");
                });

            modelBuilder.Entity("Wolfgang.AuditTrail.Entities.AuditHeader", b =>
                {
                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("header_id");

                    b.Property<DateTime>("AuditedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("audited_at_utc");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityTable")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)")
                        .HasColumnName("entity_table");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entity_type");

                    b.Property<string>("OnBehalfOfUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("on_behalf_of_user_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("operation");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("HeaderId")
                        .HasName("pk_audit_header");

                    b.HasIndex("AuditedAtUtc")
                        .HasDatabaseName("ix_audit_header_audited_at_utc");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_audit_header_transaction_id");

                    b.HasIndex("EntityType", "EntityKey")
                        .HasDatabaseName("ix_audit_header_entity_type_entity_key");

                    b.ToTable("audit_header", "core");
                });

            modelBuilder.Entity("Wolfgang.Wms.Infrastructure.Database.Settings.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CascadeMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("value")
                        .HasColumnName("cascade_mode");

                    b.Property<string>("ConfiguredValue")
                        .HasColumnType("text")
                        .HasColumnName("configured_value");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EffectiveValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effective_value");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("nextval('wms.row_version_seq')");

                    b.Property<long>("ScopeId")
                        .HasColumnType("bigint")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_setting");

                    b.HasIndex("RowVersion")
                        .HasDatabaseName("ix_setting_row_version");

                    b.HasIndex("ScopeType", "ScopeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_setting_scope_type_scope_id_key");

                    b.ToTable("setting", "core", t =>
                        {
                            t.HasTrigger("trg_setting_row_version");
                        });
                });

            modelBuilder.Entity("Wolfgang.AuditTrail.Entities.AuditDetail", b =>
                {
                    b.HasOne("Wolfgang.AuditTrail.Entities.AuditHeader", "Header")
                        .WithMany("Details")
                        .HasForeignKey("HeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_detail_header_id");

                    b.Navigation("Header");
                });

            modelBuilder.Entity("Wolfgang.AuditTrail.Entities.AuditHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
