// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Initial); index comments may be added (E3.5).
﻿using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.PostgreSql.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
