// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Sites); index comments may be added (E3.5).
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Sites); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Wolfgang.Wms.Infrastructure.Database.Conventions;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.PostgreSql.Migrations
{
    /// <inheritdoc />
    public partial class Sites : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "layout");

            migrationBuilder.CreateTable(
                name: "site",
                schema: "layout",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    code = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    code_normalized = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    name = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    time_zone = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    is_active = table.Column<bool>(type: "boolean", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp(3) with time zone", precision: 3, nullable: false),
                    updated_by = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    row_version = table.Column<long>(type: "bigint", rowVersion: true, nullable: false, defaultValueSql: "nextval('wms.row_version_seq')")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_site", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_site_row_version",
                schema: "layout",
                table: "site",
                column: "row_version");

            migrationBuilder.CreateIndex(
                name: "ux_site_code_normalized",
                schema: "layout",
                table: "site",
                column: "code_normalized",
                unique: true);

            // E5.1: the update trigger that reassigns row_version on every write outside EF and inside it.
            RowVersioning.AddUpdateTrigger(migrationBuilder, "layout", "site");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            RowVersioning.DropUpdateTrigger(migrationBuilder, "layout", "site");

            migrationBuilder.DropTable(
                name: "site",
                schema: "layout");
        }
    }
}
