<#
.SYNOPSIS
    Keeps both providers' EF migrations in step with the model (E2.4).

.DESCRIPTION
    Without -Add: runs `dotnet ef migrations has-pending-model-changes` for the SQL Server and the PostgreSQL
    migrations project and exits 1 when either has model changes without a migration. This is the CI check
    (pr.yaml, Stage 1) and the local pre-push check.

    With -Add <Name>: adds the migration <Name> to BOTH projects, so a model change never ships with one
    provider's migration only. Review the generated files; add the index comments E3.5 asks for; commit both.

    Requires the EF tool: dotnet tool install --global dotnet-ef

.EXAMPLE
    pwsh scripts/Check-Migrations.ps1

.EXAMPLE
    pwsh scripts/Check-Migrations.ps1 -Add AddZoneGroups
#>
param
(
    [string]$Add = '',

    [string]$Root = (Split-Path $PSScriptRoot -Parent)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$projects = @(
    (Join-Path $Root 'src/Wolfgang.Wms.Infrastructure.Migrations.SqlServer'),
    (Join-Path $Root 'src/Wolfgang.Wms.Infrastructure.Migrations.PostgreSql')
)

$ef = Get-Command dotnet-ef -ErrorAction SilentlyContinue
if (-not $ef)
{
    $fallback = Join-Path $HOME '.dotnet/tools/dotnet-ef'
    if ($IsWindows) { $fallback += '.exe' }
    if (-not (Test-Path $fallback)) { throw 'dotnet-ef is not installed: dotnet tool install --global dotnet-ef' }
    $ef = Get-Command $fallback
}

$failed = @()
foreach ($project in $projects)
{
    $name = Split-Path $project -Leaf
    if ($Add)
    {
        Write-Host "Adding migration '$Add' to $name"
        & $ef.Source migrations add $Add --project $project --startup-project $project
        if ($LASTEXITCODE -ne 0) { throw "dotnet ef migrations add failed for $name" }
        # dotnet ef marks the Designer and the snapshot as generated but not the migration itself; without the
        # marker the header and file-name analyzers reject it (IDE0073, MA0048). It is generated code.
        foreach ($file in Get-ChildItem (Join-Path $project 'Migrations') -Filter "*_$Add.cs")
        {
            $text = Get-Content $file.FullName -Raw
            if ($text -notmatch '<auto-generated')
            {
                Set-Content -Path $file.FullName -Value ("// <auto-generated />`n// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add $Add); index comments may be added (E3.5).`n" + $text) -NoNewline
            }
        }
        continue
    }

    Write-Host "Checking $name for model changes without a migration"
    & $ef.Source migrations has-pending-model-changes --project $project --startup-project $project
    if ($LASTEXITCODE -ne 0) { $failed += $name }
}

if ($Add) { Write-Host "Migration '$Add' added to both providers; review and commit."; exit 0 }
if ($failed.Count -gt 0)
{
    Write-Host "::error::The EF model changed without a migration for: $($failed -join ', '). Run scripts/Check-Migrations.ps1 -Add <Name> and commit both providers' migrations."
    exit 1
}
Write-Host '✅ Both providers'' migrations match the model'
