#!/usr/bin/env pwsh
#Requires -Version 7.0

<#
.SYNOPSIS
    Regenerates THIRD-PARTY-NOTICES.md from the NuGet packages the shipped projects depend on.
.DESCRIPTION
    Runs the nuget-license tool (the same tool the license-audit workflow uses) over every project under
    src/ and writes one table of package, version, license and project URL to THIRD-PARTY-NOTICES.md.
    Run it whenever a package is added, removed or bumped; the file is committed so the notice ships with
    the source (E1.6).

    Projects whose target framework needs a workload this machine lacks (for example net10.0-android) are
    skipped with a warning; run on a machine with the workload, or in CI, to include them.
.PARAMETER Root
    Repository root. Default: the parent of this script's directory.
.PARAMETER Check
    Do not write; exit 1 if the file on disk differs from what would be generated (CI mode).
#>

[CmdletBinding()]
param
(
    [string]$Root = (Split-Path -Parent $PSScriptRoot),
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Global dotnet tools live in ~/.dotnet/tools, which is not always on PATH (fresh shells, CI runners).
$tool = (Get-Command nuget-license -ErrorAction SilentlyContinue)?.Source
if (-not $tool)
{
    $candidate = Join-Path $HOME '.dotnet' 'tools' $(if ($IsWindows) { 'nuget-license.exe' } else { 'nuget-license' })
    if (Test-Path $candidate) { $tool = $candidate }
}
if (-not $tool)
{
    throw 'nuget-license is not installed: dotnet tool install --global nuget-license'
}

$projects = Get-ChildItem (Join-Path $Root 'src') -Recurse -Filter *.csproj | Sort-Object FullName
$packages = @{}
$skipped = @()
foreach ($project in $projects)
{
    $json = & $tool -i $project.FullName -t -o JsonPretty 2>&1
    if ($LASTEXITCODE -ne 0)
    {
        $skipped += $project.BaseName
        Write-Warning "skipped $($project.BaseName): $(($json | Select-Object -Last 1) -join ' ')"
        continue
    }

    foreach ($entry in (($json | Out-String) | ConvertFrom-Json))
    {
        $key = "$($entry.PackageId)|$($entry.PackageVersion)"
        if (-not $packages.ContainsKey($key))
        {
            $packages[$key] = [pscustomobject]@{
                Id      = $entry.PackageId
                Version = $entry.PackageVersion
                License = $(if ($entry.License) { $entry.License } elseif ($entry.LicenseUrl) { $entry.LicenseUrl } else { 'see package' })
                Url     = $(if ($entry.PackageProjectUrl) { $entry.PackageProjectUrl } else { "https://www.nuget.org/packages/$($entry.PackageId)/$($entry.PackageVersion)" })
                Authors = $entry.Authors
            }
        }
    }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# Third-party notices')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Generated by `scripts/Generate-ThirdPartyNotices.ps1` from the NuGet dependencies of every project under `src/`.')
[void]$sb.AppendLine('Do not edit by hand; re-run the script after changing a package reference.')
[void]$sb.AppendLine()
if ($skipped.Count -gt 0)
{
    [void]$sb.AppendLine("Projects not included in this run (workload missing on the generating machine): $($skipped -join ', ').")
    [void]$sb.AppendLine()
}
[void]$sb.AppendLine('| Package | Version | License | Authors | Project |')
[void]$sb.AppendLine('|---|---|---|---|---|')
foreach ($pkg in ($packages.Values | Sort-Object Id, Version))
{
    [void]$sb.AppendLine("| $($pkg.Id) | $($pkg.Version) | $($pkg.License) | $($pkg.Authors) | $($pkg.Url) |")
}
$content = $sb.ToString()

$target = Join-Path $Root 'THIRD-PARTY-NOTICES.md'
if ($Check)
{
    $existing = if (Test-Path $target) { Get-Content $target -Raw } else { '' }
    if ($existing.Replace("`r`n", "`n") -ne $content.Replace("`r`n", "`n"))
    {
        Write-Host '::error::THIRD-PARTY-NOTICES.md is out of date; run scripts/Generate-ThirdPartyNotices.ps1 and commit the result.'
        exit 1
    }
    Write-Host 'THIRD-PARTY-NOTICES.md is up to date.'
    exit 0
}

Set-Content -Path $target -Value $content -NoNewline
Write-Host "wrote $target ($($packages.Count) package(s); $($projects.Count - $skipped.Count) of $($projects.Count) project(s))"
