// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Users); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Wolfgang.Wms.Infrastructure.Database.Conventions;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class Users : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "user",
                schema: "core",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    user_name = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    user_name_normalized = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    display_name = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    password_hash = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    must_change_password = table.Column<bool>(type: "bit", nullable: false),
                    is_disabled = table.Column<bool>(type: "bit", nullable: false),
                    is_local_admin = table.Column<bool>(type: "bit", nullable: false),
                    failed_login_count = table.Column<int>(type: "int", nullable: false),
                    locked_until = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: true),
                    sessions_valid_after = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: true),
                    created_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: false),
                    updated_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: false),
                    row_version = table.Column<long>(type: "bigint", rowVersion: true, nullable: false, defaultValueSql: "NEXT VALUE FOR [wms].[row_version_seq]")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_user", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_user_row_version",
                schema: "core",
                table: "user",
                column: "row_version");

            // Serves: sign-in by name (case-insensitive through the normalised column) and its uniqueness.
            migrationBuilder.CreateIndex(
                name: "ux_user_user_name_normalized",
                schema: "core",
                table: "user",
                column: "user_name_normalized",
                unique: true);

            // E5.1: the update trigger that reassigns row_version on every write outside EF and inside it.
            RowVersioning.AddUpdateTrigger(migrationBuilder, "core", "user");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            RowVersioning.DropUpdateTrigger(migrationBuilder, "core", "user");

            migrationBuilder.DropTable(
                name: "user",
                schema: "core");
        }
    }
}
