// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add LocalLoginGate); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Wolfgang.Wms.Infrastructure.Database.Conventions;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class LocalLoginGate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "local_login_gate",
                schema: "core",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    sso_verified_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: true),
                    sso_verified_provider = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true),
                    unlocked_until = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: true),
                    unlocked_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: true),
                    unlocked_by = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    locked_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: true),
                    locked_by = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    row_version = table.Column<long>(type: "bigint", rowVersion: true, nullable: false, defaultValueSql: "NEXT VALUE FOR [wms].[row_version_seq]")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_local_login_gate", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_local_login_gate_row_version",
                schema: "core",
                table: "local_login_gate",
                column: "row_version");

            // E5.1: the update trigger that reassigns row_version on every write outside EF and inside it.
            RowVersioning.AddUpdateTrigger(migrationBuilder, "core", "local_login_gate");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            RowVersioning.DropUpdateTrigger(migrationBuilder, "core", "local_login_gate");

            migrationBuilder.DropTable(
                name: "local_login_gate",
                schema: "core");
        }
    }
}
