// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Settings); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Wolfgang.Wms.Infrastructure.Database.Conventions;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class Settings : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "core");

            migrationBuilder.CreateTable(
                name: "setting",
                schema: "core",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    scope_type = table.Column<string>(type: "nvarchar(16)", maxLength: 16, nullable: false),
                    scope_id = table.Column<long>(type: "bigint", nullable: false),
                    key = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    configured_value = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    effective_value = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    updated_by = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    updated_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: false),
                    row_version = table.Column<long>(type: "bigint", rowVersion: true, nullable: false, defaultValueSql: "NEXT VALUE FOR [wms].[row_version_seq]"),
                    deleted_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_setting", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_setting_row_version",
                schema: "core",
                table: "setting",
                column: "row_version");

            // Serves: the accessor's lookup of one setting at one scope; also the uniqueness E6.2 requires.
            migrationBuilder.CreateIndex(
                name: "ux_setting_scope_type_scope_id_key",
                schema: "core",
                table: "setting",
                columns: new[] { "scope_type", "scope_id", "key" },
                unique: true);

            // E5.1: the update trigger that reassigns row_version on every write outside EF and inside it.
            RowVersioning.AddUpdateTrigger(migrationBuilder, "core", "setting");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            RowVersioning.DropUpdateTrigger(migrationBuilder, "core", "setting");

            migrationBuilder.DropTable(
                name: "setting",
                schema: "core");
        }
    }
}
