// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add CascadeMode); index comments may be added (E3.5).
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class CascadeMode : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "cascade_mode",
                schema: "core",
                table: "setting",
                type: "nvarchar(16)",
                maxLength: 16,
                nullable: false,
                defaultValue: "value");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "cascade_mode",
                schema: "core",
                table: "setting");
        }
    }
}
