// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Locations); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Wolfgang.Wms.Infrastructure.Database.Conventions;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class Locations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "location",
                schema: "layout",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    site_id = table.Column<long>(type: "bigint", nullable: false),
                    zone_id = table.Column<long>(type: "bigint", nullable: false),
                    code = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false),
                    code_normalized = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false),
                    barcode = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    walk_sequence = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false),
                    is_pickable = table.Column<bool>(type: "bit", nullable: false),
                    is_active = table.Column<bool>(type: "bit", nullable: false),
                    updated_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: false),
                    updated_by = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    row_version = table.Column<long>(type: "bigint", rowVersion: true, nullable: false, defaultValueSql: "NEXT VALUE FOR [wms].[row_version_seq]")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_location", x => x.id);
                    table.ForeignKey(
                        name: "fk_location_site_id",
                        column: x => x.site_id,
                        principalSchema: "layout",
                        principalTable: "site",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_location_zone_id",
                        column: x => x.zone_id,
                        principalSchema: "layout",
                        principalTable: "zone",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_location_row_version",
                schema: "layout",
                table: "location",
                column: "row_version");

            migrationBuilder.CreateIndex(
                name: "ix_location_site_id_walk_sequence_id",
                schema: "layout",
                table: "location",
                columns: new[] { "site_id", "walk_sequence", "id" });

            migrationBuilder.CreateIndex(
                name: "ix_location_zone_id_walk_sequence_id",
                schema: "layout",
                table: "location",
                columns: new[] { "zone_id", "walk_sequence", "id" });

            migrationBuilder.CreateIndex(
                name: "ux_location_site_id_barcode",
                schema: "layout",
                table: "location",
                columns: new[] { "site_id", "barcode" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ux_location_site_id_code_normalized",
                schema: "layout",
                table: "location",
                columns: new[] { "site_id", "code_normalized" },
                unique: true);

            // E5.1: the update trigger that reassigns row_version on every write outside EF and inside it.
            RowVersioning.AddUpdateTrigger(migrationBuilder, "layout", "location");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            RowVersioning.DropUpdateTrigger(migrationBuilder, "layout", "location");

            migrationBuilder.DropTable(
                name: "location",
                schema: "layout");
        }
    }
}
