// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Audit); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class Audit : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "audit_header",
                schema: "core",
                columns: table => new
                {
                    header_id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    transaction_id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    audited_at_utc = table.Column<DateTime>(type: "datetime2(6)", precision: 6, nullable: false),
                    user_id = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    on_behalf_of_user_id = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    entity_type = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    entity_table = table.Column<string>(type: "nvarchar(384)", maxLength: 384, nullable: false),
                    entity_key = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    operation = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_audit_header", x => x.header_id);
                });

            migrationBuilder.CreateTable(
                name: "audit_detail",
                schema: "core",
                columns: table => new
                {
                    detail_id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    header_id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    column_name = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    value_text = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    value_type = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_audit_detail", x => x.detail_id);
                    table.ForeignKey(
                        name: "fk_audit_detail_header_id",
                        column: x => x.header_id,
                        principalSchema: "core",
                        principalTable: "audit_header",
                        principalColumn: "header_id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_audit_detail_column_name",
                schema: "core",
                table: "audit_detail",
                column: "column_name");

            migrationBuilder.CreateIndex(
                name: "ix_audit_detail_header_id",
                schema: "core",
                table: "audit_detail",
                column: "header_id");

            migrationBuilder.CreateIndex(
                name: "ix_audit_header_audited_at_utc",
                schema: "core",
                table: "audit_header",
                column: "audited_at_utc");

            migrationBuilder.CreateIndex(
                name: "ix_audit_header_entity_type_entity_key",
                schema: "core",
                table: "audit_header",
                columns: new[] { "entity_type", "entity_key" });

            migrationBuilder.CreateIndex(
                name: "ix_audit_header_transaction_id",
                schema: "core",
                table: "audit_header",
                column: "transaction_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "audit_detail",
                schema: "core");

            migrationBuilder.DropTable(
                name: "audit_header",
                schema: "core");
        }
    }
}
