// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add Organization); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Wolfgang.Wms.Infrastructure.Database.Conventions;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class Organization : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "organization",
                schema: "core",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    name = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    legal_name = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    logo_data_url = table.Column<string>(type: "nvarchar(max)", maxLength: 262144, nullable: true),
                    time_zone = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false),
                    locale = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false),
                    address_line1 = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    address_line2 = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    address_city = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    address_region = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    address_postal_code = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true),
                    address_country = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    primary_contact_name = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    primary_contact_email = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    primary_contact_phone = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    support_contact_name = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    support_contact_email = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    support_contact_phone = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    updated_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: false),
                    updated_by = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    row_version = table.Column<long>(type: "bigint", rowVersion: true, nullable: false, defaultValueSql: "NEXT VALUE FOR [wms].[row_version_seq]")
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_organization", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_organization_row_version",
                schema: "core",
                table: "organization",
                column: "row_version");

            // E5.1: the update trigger that reassigns row_version on every write outside EF and inside it.
            RowVersioning.AddUpdateTrigger(migrationBuilder, "core", "organization");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            RowVersioning.DropUpdateTrigger(migrationBuilder, "core", "organization");

            migrationBuilder.DropTable(
                name: "organization",
                schema: "core");
        }
    }
}
