// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add ExternalAccounts); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Wolfgang.Wms.Infrastructure.Database.Conventions;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class ExternalAccounts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "provider",
                schema: "core",
                table: "user",
                type: "nvarchar(32)",
                maxLength: 32,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "provider_subject",
                schema: "core",
                table: "user",
                type: "nvarchar(256)",
                maxLength: 256,
                nullable: true);

            migrationBuilder.CreateTable(
                name: "group_role_mapping",
                schema: "core",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    provider = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: false),
                    group_key = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    role_id = table.Column<long>(type: "bigint", nullable: false),
                    site_id = table.Column<long>(type: "bigint", nullable: true),
                    updated_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: false),
                    updated_by = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    row_version = table.Column<long>(type: "bigint", rowVersion: true, nullable: false, defaultValueSql: "NEXT VALUE FOR [wms].[row_version_seq]"),
                    signature = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_group_role_mapping", x => x.id);
                    table.ForeignKey(
                        name: "fk_group_role_mapping_role_id",
                        column: x => x.role_id,
                        principalSchema: "core",
                        principalTable: "role",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ux_user_provider_provider_subject",
                schema: "core",
                table: "user",
                columns: new[] { "provider", "provider_subject" },
                unique: true,
                filter: "[provider] IS NOT NULL AND [provider_subject] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_group_role_mapping_provider_group_key_role_id_site_id",
                schema: "core",
                table: "group_role_mapping",
                columns: new[] { "provider", "group_key", "role_id", "site_id" });

            migrationBuilder.CreateIndex(
                name: "ix_group_role_mapping_role_id",
                schema: "core",
                table: "group_role_mapping",
                column: "role_id");

            migrationBuilder.CreateIndex(
                name: "ix_group_role_mapping_row_version",
                schema: "core",
                table: "group_role_mapping",
                column: "row_version");

            // E5.1: the update trigger that reassigns row_version on every write outside EF and inside it.
            RowVersioning.AddUpdateTrigger(migrationBuilder, "core", "group_role_mapping");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            RowVersioning.DropUpdateTrigger(migrationBuilder, "core", "group_role_mapping");

            migrationBuilder.DropTable(
                name: "group_role_mapping",
                schema: "core");

            migrationBuilder.DropIndex(
                name: "ux_user_provider_provider_subject",
                schema: "core",
                table: "user");

            migrationBuilder.DropColumn(
                name: "provider",
                schema: "core",
                table: "user");

            migrationBuilder.DropColumn(
                name: "provider_subject",
                schema: "core",
                table: "user");
        }
    }
}
