// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wolfgang.Wms.Infrastructure.Database;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20260920035312_RowVersionSequence")]
    partial class RowVersionSequence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("row_version_seq", "wms");
#pragma warning restore 612, 618
        }
    }
}
