// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add IntegritySignatures); index comments may be added (E3.5).
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class IntegritySignatures : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "signature",
                schema: "core",
                table: "user_role",
                type: "nvarchar(64)",
                maxLength: 64,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "signature",
                schema: "core",
                table: "user",
                type: "nvarchar(64)",
                maxLength: 64,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "signature",
                schema: "core",
                table: "role",
                type: "nvarchar(64)",
                maxLength: 64,
                nullable: true);

            migrationBuilder.CreateTable(
                name: "integrity_key",
                schema: "wms",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    protected_key = table.Column<string>(type: "nvarchar(512)", maxLength: 512, nullable: false),
                    created_at = table.Column<DateTime>(type: "datetime2(3)", precision: 3, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_integrity_key", x => x.id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "integrity_key",
                schema: "wms");

            migrationBuilder.DropColumn(
                name: "signature",
                schema: "core",
                table: "user_role");

            migrationBuilder.DropColumn(
                name: "signature",
                schema: "core",
                table: "user");

            migrationBuilder.DropColumn(
                name: "signature",
                schema: "core",
                table: "role");
        }
    }
}
