// <auto-generated />
// Generated by dotnet ef (scripts/Check-Migrations.ps1 -Add RowVersionSequence); index comments may be added (E3.5).
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    /// <inheritdoc />
    public partial class RowVersionSequence : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "wms");

            migrationBuilder.CreateSequence(
                name: "row_version_seq",
                schema: "wms");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropSequence(
                name: "row_version_seq",
                schema: "wms");
        }
    }
}
