// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wolfgang.Wms.Infrastructure.Database;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    partial class WmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("row_version_seq", "wms");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_key");

                    b.ToTable("data_protection_key", "wms");
                });

            modelBuilder.Entity("Wolfgang.AuditTrail.Entities.AuditDetail", b =>
                {
                    b.Property<long>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DetailId"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("column_name");

                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("header_id");

                    b.Property<string>("ValueText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value_text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("value_type");

                    b.HasKey("DetailId")
                        .HasName("pk_audit_detail");

                    b.HasIndex("ColumnName")
                        .HasDatabaseName("ix_audit_detail_column_name");

                    b.HasIndex("HeaderId")
                        .HasDatabaseName("ix_audit_detail_header_id");

                    b.ToTable("audit_detail", "core");
                });

            modelBuilder.Entity("Wolfgang.AuditTrail.Entities.AuditHeader", b =>
                {
                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("header_id");

                    b.Property<DateTime>("AuditedAtUtc")
                        .HasPrecision(6)
                        .HasColumnType("datetime2(6)")
                        .HasColumnName("audited_at_utc");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityTable")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("nvarchar(384)")
                        .HasColumnName("entity_table");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("entity_type");

                    b.Property<string>("OnBehalfOfUserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("on_behalf_of_user_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("operation");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_id");

                    b.HasKey("HeaderId")
                        .HasName("pk_audit_header");

                    b.HasIndex("AuditedAtUtc")
                        .HasDatabaseName("ix_audit_header_audited_at_utc");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_audit_header_transaction_id");

                    b.HasIndex("EntityType", "EntityKey")
                        .HasDatabaseName("ix_audit_header_entity_type_entity_key");

                    b.ToTable("audit_header", "core");
                });

            modelBuilder.Entity("Wolfgang.Wms.Infrastructure.Database.Settings.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CascadeMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("value")
                        .HasColumnName("cascade_mode");

                    b.Property<string>("ConfiguredValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("configured_value");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EffectiveValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("effective_value");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("key");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("NEXT VALUE FOR [wms].[row_version_seq]");

                    b.Property<long>("ScopeId")
                        .HasColumnType("bigint")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("scope_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_setting");

                    b.HasIndex("RowVersion")
                        .HasDatabaseName("ix_setting_row_version");

                    b.HasIndex("ScopeType", "ScopeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_setting_scope_type_scope_id_key");

                    b.ToTable("setting", "core", t =>
                        {
                            t.HasTrigger("trg_setting_row_version");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Wolfgang.Wms.Infrastructure.Identity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("display_name");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_count");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("IsLocalAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_local_admin");

                    b.Property<DateTime?>("LockedUntil")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("NEXT VALUE FOR [wms].[row_version_seq]");

                    b.Property<DateTime?>("SessionsValidAfter")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("sessions_valid_after");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserNameNormalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name_normalized");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("RowVersion")
                        .HasDatabaseName("ix_user_row_version");

                    b.HasIndex("UserNameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_user_user_name_normalized");

                    b.ToTable("user", "core", t =>
                        {
                            t.HasTrigger("trg_user_row_version");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Wolfgang.AuditTrail.Entities.AuditDetail", b =>
                {
                    b.HasOne("Wolfgang.AuditTrail.Entities.AuditHeader", "Header")
                        .WithMany("Details")
                        .HasForeignKey("HeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_detail_header_id");

                    b.Navigation("Header");
                });

            modelBuilder.Entity("Wolfgang.AuditTrail.Entities.AuditHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
