// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wolfgang.Wms.Infrastructure.Database;

#nullable disable

namespace Wolfgang.Wms.Infrastructure.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    partial class WmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("row_version_seq", "wms");

            modelBuilder.Entity("Wolfgang.Wms.Infrastructure.Database.Settings.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfiguredValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("configured_value");

                    b.Property<DateTime?>("DeletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EffectiveValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("effective_value");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("key");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("NEXT VALUE FOR [wms].[row_version_seq]");

                    b.Property<long>("ScopeId")
                        .HasColumnType("bigint")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("scope_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_setting");

                    b.HasIndex("RowVersion")
                        .HasDatabaseName("ix_setting_row_version");

                    b.HasIndex("ScopeType", "ScopeId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_setting_scope_type_scope_id_key");

                    b.ToTable("setting", "core", t =>
                        {
                            t.HasTrigger("trg_setting_row_version");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });
#pragma warning restore 612, 618
        }
    }
}
