// Copyright (c) Chris Wolfgang. All rights reserved. SPDX-License-Identifier: LicenseRef-TBD

using System.Globalization;
using System.Text;
using Wolfgang.Wms.Core.Modules;
using Wolfgang.Wms.Core.Settings;
using Wolfgang.Wms.Domain.Keys;

namespace Wolfgang.Wms.Core.Docs;

/// <summary>
/// The reference pages generated from the product itself (E83.2, E83.3): settings, permissions, error
/// codes and modules, rendered as Markdown for the docs site from the same registries the host serves.
/// A test keeps the committed pages equal to the generated ones, so no setting, permission or code is ever
/// missing from the docs and the diff is visible in the pull request that changes them.
/// </summary>
public static class ReferencePages
{
    private const string Banner = "<!-- Generated by ReferenceDocsTests from the product's registries; do not edit by hand. Rewrite with WMS_UPDATE_REFERENCE_DOCS=1. -->\n\n";



    /// <summary>
    /// Every setting of every module, by name.
    /// </summary>
    /// <exception cref="ArgumentNullException"><paramref name="modules"/> is null.</exception>
    public static string Settings(ModuleCollection modules)
    {
        ArgumentNullException.ThrowIfNull(modules);

        var text = new StringBuilder(Banner);
        text.Append("# Settings reference\n\nEvery setting the product knows, from every module's declaration (E6.1). Scopes are where a value may be configured; the value in force at a scope is its own, else the nearest ancestor's, else the default.\n\n");
        text.Append("| Setting | Kind | Scopes | Default | Description |\n|---|---|---|---|---|\n");
        foreach (var setting in modules.Modules.SelectMany(m => m.Settings).OrderBy(s => s.Name, StringComparer.Ordinal).Select(SettingDescriptor.Of))
        {
            var notes = string.Concat(setting.RequiresRestart ? " Requires a restart." : string.Empty, setting.TriggersDeviceResync ? " Triggers a device resync." : string.Empty, setting.Choices is { Count: > 0 } ? $" One of: {string.Join(", ", setting.Choices.Select(c => $"`{c}`"))}." : string.Empty);
            text.Append(CultureInfo.InvariantCulture, $"| `{setting.Name}` | {setting.Kind} | {string.Join(", ", setting.Scopes)} | {Cell(setting.Default)} | {Cell(setting.Description)}{notes} |\n");
        }

        return text.ToString();
    }



    /// <summary>
    /// Every permission of every module with the built-in roles that hold it by default.
    /// </summary>
    /// <exception cref="ArgumentNullException"><paramref name="modules"/> is null.</exception>
    public static string Permissions(ModuleCollection modules)
    {
        ArgumentNullException.ThrowIfNull(modules);

        var text = new StringBuilder(Banner);
        text.Append("# Permissions reference\n\nEvery permission an endpoint checks (E10.1), by module, with the built-in roles that carry it out of the box. The Administrator role holds every permission.\n\n");
        text.Append("| Permission | Module | Default roles | Description |\n|---|---|---|---|\n");
        foreach (var (module, permission) in modules.Modules.SelectMany(m => m.Permissions.Select(p => (m.Name, p))).OrderBy(x => x.p.Name, StringComparer.Ordinal))
        {
            var roles = permission.DefaultRoles.Count == 0 ? "—" : string.Join(", ", permission.DefaultRoles.Select(r => r.ToString()));
            text.Append(CultureInfo.InvariantCulture, $"| `{permission.Name}` | {module} | {roles} | {Cell(permission.Description)} |\n");
        }

        return text.ToString();
    }



    /// <summary>
    /// Every error code, by area, with its HTTP status, severity, message and troubleshooting link.
    /// </summary>
    /// <exception cref="ArgumentNullException"><paramref name="codes"/> is null.</exception>
    public static string ErrorCodes(IReadOnlyList<ErrorCode> codes)
    {
        ArgumentNullException.ThrowIfNull(codes);

        var text = new StringBuilder(Banner);
        text.Append("# Error codes reference\n\nEvery error the API answers with (E82.3): `application/problem+json` whose `code`, `status` and `severity` come from the typed code and whose `type` points at the troubleshooting entry. Codes are stable; messages may carry placeholders the handler fills.\n\n");
        text.Append("| Code | Status | Severity | Message | Help |\n|---|---|---|---|---|\n");
        foreach (var code in codes.OrderBy(c => c.Code, StringComparer.Ordinal))
        {
            text.Append(CultureInfo.InvariantCulture, $"| `{code.Code}` | {code.HttpStatus} | {code.Severity.ToString().ToLowerInvariant()} | {Cell(code.MessageTemplate)} | [{code.DocsAnchor}](../troubleshooting.md#{code.DocsAnchor}) |\n");
        }

        return text.ToString();
    }



    /// <summary>
    /// Every module with what it contributes.
    /// </summary>
    /// <exception cref="ArgumentNullException"><paramref name="modules"/> is null.</exception>
    public static string Modules(ModuleCollection modules)
    {
        ArgumentNullException.ThrowIfNull(modules);

        var text = new StringBuilder(Banner);
        text.Append("# Modules reference\n\nEvery module the API host registers (E1.10) and what it contributes: settings, permissions, license features, jobs, issue types and error codes are all declared on the module descriptor, which is where the registries and these pages read from.\n\n");
        text.Append("| Module | Settings | Permissions | License features | Jobs | Issue types | Error codes |\n|---|---|---|---|---|---|---|\n");
        foreach (var module in modules.Modules.OrderBy(m => m.Name, StringComparer.Ordinal))
        {
            text.Append(CultureInfo.InvariantCulture, $"| `{module.Name}` | {module.Settings.Count} | {module.Permissions.Count} | {module.LicenseFeatures.Count} | {module.Jobs.Count} | {module.IssueTypes.Count} | {module.ErrorCodes.Count} |\n");
        }

        return text.ToString();
    }



    /// <summary>
    /// The codes with no entry on the troubleshooting page: an entry is the anchor
    /// <c>&lt;a id="{DocsAnchor}"&gt;&lt;/a&gt;</c> the problem's <c>type</c> URI points at.
    /// </summary>
    /// <exception cref="ArgumentNullException">An argument is null.</exception>
    public static IReadOnlyList<ErrorCode> MissingTroubleshootingEntries(string troubleshootingPage, IReadOnlyList<ErrorCode> codes)
    {
        ArgumentNullException.ThrowIfNull(troubleshootingPage);
        ArgumentNullException.ThrowIfNull(codes);

        return codes.Where(c => !troubleshootingPage.Contains($"<a id=\"{c.DocsAnchor}\"></a>", StringComparison.Ordinal)).ToList();
    }



    /// <summary>
    /// The import formats page (E16.6): one section per entity type with its route, natural key, default
    /// policy, rules and the fields of the row type the API deserializes.
    /// </summary>
    /// <exception cref="ArgumentNullException"><paramref name="formats"/> is null.</exception>
    public static string ImportFormats(IReadOnlyList<Imports.ImportFormat> formats)
    {
        ArgumentNullException.ThrowIfNull(formats);

        var text = new StringBuilder(Banner);
        text.Append("# Import formats reference\n\nThe master data files the importer accepts (E16.6): one file per entity type, a JSON array of the objects below (the same objects the API takes, plus `action`), loaded by `POST` to the route with `policy=all_or_nothing|accept_valid_rows|validate_only` (the default differs per entity) and answered with one result shape: counts plus a line per row (`format=csv` for the rows as CSV). Every import is an idempotent upsert by the natural key; `action: Delete` retires the row. Files are loaded in the order listed.\n\n");
        foreach (var format in formats)
        {
            text.Append(CultureInfo.InvariantCulture, $"## `{format.Entity}`\n\n| | |\n|---|---|\n| Route | `POST {format.Route}` |\n| Natural key | `{format.NaturalKey}` |\n| Default policy | `{Imports.ImportRules.Name(format.DefaultPolicy)}` |\n| Row type | `{format.RowType.Name}` |\n\n{Cell(format.Notes)}\n\n");
            text.Append("| Field | Type | Required | Default | Notes |\n|---|---|---|---|---|\n");
            foreach (var field in format.Fields)
            {
                text.Append(CultureInfo.InvariantCulture, $"| `{field.Name}` | {Cell(field.Type)} | {(field.Required ? "yes" : "no")} | {(field.Default is null ? string.Empty : "`" + Cell(field.Default) + "`")} | {Cell(field.Notes)} |\n");
            }

            text.Append('\n');
        }

        return text.ToString();
    }



    private static string Cell(string text)
    {
        return text.Replace("|", "\\|", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal);
    }
}
